# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "GoogleReaderApi"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Toon Willems"]
  s.date = "2012-07-03"
  s.description = "a google reader api (unofficial) written in ruby"
  s.email = "willemstoon@gmail.com"
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "GoogleReaderApi.gemspec",
    "License",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "lib/google-reader-api/api.rb",
    "lib/google-reader-api/cache.rb",
    "lib/google-reader-api/entry.rb",
    "lib/google-reader-api/feed.rb",
    "lib/google-reader-api/google_login.rb",
    "lib/google-reader-api/rss_utils.rb",
    "lib/google-reader-api/subscription_list.rb",
    "lib/google-reader-api/user.rb",
    "lib/google_reader_api.rb"
  ]
  s.homepage = "http://github.com/nudded/GoogleReaderAPI"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "a google reader api (unofficial) written in ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

